apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netdata
  namespace: netdata
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/agjmills/kubernetes-homelab-apps/charts
    chart: netdata
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true