---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - ref: values
      repoURL: https://github.com/agjmills/kubernetes-homelab-apps
      targetRevision: HEAD
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.5.0
      helm:
        valueFiles:
          - $values/values/services/argo/values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd