apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invoiceninja
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: invoiceninja
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
    - ref: values
      repoURL: https://github.com/agjmills/kubernetes-homelab-apps
      targetRevision: HEAD
    - repoURL: https://github.com/invoiceninja/dockerfiles.git
      path: charts/invoiceninja
      targetRevision: 5.10.26
      helm:
        valueFiles:
          - $values/values/services/invoiceninja/values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true