apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/agjmills/kubernetes-homelab-apps
    targetRevision: HEAD
    path: charts/jellyfin

    helm:
      valueFiles:
      - values.yaml

  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
