---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-secret-generator
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: kubernetes-secret-generator
      repoURL: https://helm.mittwald.de
      targetRevision: 3.4.0
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: kubernetes-secret-generator