---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - ref: values
      repoURL: https://github.com/agjmills/kubernetes-homelab-apps
      targetRevision: HEAD
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.7.0
      helm:
        valueFiles:
          - $values/values/services/longhorn/values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system
---
# Generate a password with this:
# USER=<USERNAME_HERE>; PASSWORD=<PASSWORD_HERE>; echo "${USER}:$(openssl passwd -stdin -apr1 <<< ${PASSWORD})" >> auth
# Store it as a secret in the cluster:
# kubectl -n longhorn-system create secret generic basic-auth --from-file=auth
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-auth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: basic-auth