apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - ref: values
      repoURL: https://github.com/agjmills/kubernetes-homelab-apps
      targetRevision: HEAD
    - chart: lonrhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.7.0
      helm:
        valueFiles:
          - $values/values/services/longhorn/values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system
