apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-netdata
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: netdata
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: netdata
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true