image:
  tag: edge

parent:
  envFrom: 
    ## Create it with: kubectl create secret generic netdata --from-literal="NETDATA_CLAIM_TOKEN=<token>"
    - secretRef:
      name: netdata
  claiming:
    enabled: true
    token: ""
    rooms: ""

child:
  envFrom: 
    - secretRef:
      name: netdata
  claiming:
    enabled: true
    token: ""
    rooms: ""

k8sState:
  envFrom:
    - secretRef:
      name: netdata