persistence:
  config:
    enabled: true
    retain: true
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi

  # Optional - Download location - Allows dedicated volume for storage of downloaded files.
  downloads:
    enabled: true
    mountPath: /downloads
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 10Gi

  # Optional - Allows linking to an existing media library scraping location.
  media:
    enabled: true
    mountPath: /media
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 10Gi

ingress:
  main:
    enabled: false
    hosts:
      - host: download.asdfx.us
        paths:
          - path: /
